[package]
name = "cloudflare-rust-workers"
version = "0.1.0"
edition = "2021"
description = "Cloudflare Workers sample project built with Rust and WebAssembly"
repository = "https://github.com/myzkey/cloudflare-rust-workers"
license = "MIT"

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
worker = "0.6"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
